platform :ios, '8.0'

target 'iPitch' do
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'
  pod 'GoogleMaps'	
  pod 'ObjectMapper', '~> 2.2'
  pod 'IQKeyboardManagerSwift'
end
